2019-12-08 16:00:51.147 +01:00 [INF] Trying
2019-12-08 16:00:52.556 +01:00 [ERR] Something went wrong
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<>c.<Update>b__21_0(UpdateTranslator ut)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__153_0()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   a következő helyen: System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
   a következő helyen: System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   a következő helyen: System.Data.Entity.DbContext.SaveChanges()
   a következő helyen: ORM_Core.Start.Main(String[] args) hely: C:\Users\csont\source\repos\ORM_Core\ORM_Core\Start.cs, sor: 71
2019-12-08 16:00:52.585 +01:00 [ERR] Something went wrong
System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<>c.<Update>b__21_0(UpdateTranslator ut)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__153_0()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   a következő helyen: System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
2019-12-08 16:00:52.607 +01:00 [ERR] Something went wrong
MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
2019-12-08 16:00:52.618 +01:00 [INF] Done trying
2019-12-08 16:03:24.826 +01:00 [INF] Trying
2019-12-08 16:03:47.277 +01:00 [INF] Calling downstrem sync
2019-12-08 16:03:47.652 +01:00 [INF] Done trying
2019-12-08 16:14:33.327 +01:00 [INF] Trying
2019-12-08 16:14:36.182 +01:00 [ERR] Something went wrong
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<>c.<Update>b__21_0(UpdateTranslator ut)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__153_0()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   a következő helyen: System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
   a következő helyen: System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   a következő helyen: System.Data.Entity.DbContext.SaveChanges()
   a következő helyen: ORM_Core.Start.Main(String[] args) hely: C:\Users\csont\source\repos\ORM_Core\ORM_Core\Start.cs, sor: 71
2019-12-08 16:14:36.204 +01:00 [ERR] Something went wrong
System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<>c.<Update>b__21_0(UpdateTranslator ut)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__153_0()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   a következő helyen: System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
2019-12-08 16:14:36.225 +01:00 [ERR] Something went wrong
MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
2019-12-08 16:14:36.237 +01:00 [INF] Done trying
2019-12-08 16:15:38.709 +01:00 [INF] Trying
2019-12-08 16:15:40.062 +01:00 [ERR] Something went wrong
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<>c.<Update>b__21_0(UpdateTranslator ut)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__153_0()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   a következő helyen: System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
   a következő helyen: System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   a következő helyen: System.Data.Entity.DbContext.SaveChanges()
   a következő helyen: ORM_Core.Start.Main(String[] args) hely: C:\Users\csont\source\repos\ORM_Core\ORM_Core\Start.cs, sor: 71
2019-12-08 16:15:40.083 +01:00 [ERR] Something went wrong
System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<>c.<Update>b__21_0(UpdateTranslator ut)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   a következő helyen: System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__153_0()
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass148_0.<SaveChangesInternal>b__0()
   a következő helyen: System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   a következő helyen: System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   a következő helyen: System.Data.Entity.Internal.InternalContext.SaveChanges()
2019-12-08 16:15:40.109 +01:00 [ERR] Something went wrong
MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '818321431' for key 'users_label_uindex'
   a következő helyen: MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   a következő helyen: MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   a következő helyen: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   a következő helyen: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   a következő helyen: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   a következő helyen: System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   a következő helyen: System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   a következő helyen: System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   a következő helyen: System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
2019-12-08 16:15:40.119 +01:00 [INF] Done trying
2019-12-08 16:16:27.101 +01:00 [INF] Trying
2019-12-08 16:16:43.342 +01:00 [INF] Calling downstream sync
2019-12-08 16:16:43.724 +01:00 [INF] Done trying
